[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'vim-scripts/Lucius'
hook_add = '''
  set background=dark
  augroup colorschemeSetting
    autocmd!
    autocmd VimEnter * ++nested colorscheme lucius
  augroup END
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat'
		\ }
 
	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	set noshowmode
'''
[[plugins]]
repo = 'chase/vim-ansible-yaml'
